#############################################################################
# Makefile for building: RCcompat3
# Generated by qmake (2.01a) (Qt 4.6.3) on: Fri Mar 22 17:11:59 2013
# Project:  RCcompat3.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile RCcompat3.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		configurator.cpp \
		helpabout.cpp \
		operationguide.cpp \
		redcellantigens.cpp moc_mainwindow.cpp \
		moc_configurator.cpp \
		moc_helpabout.cpp \
		moc_operationguide.cpp \
		moc_redcellantigens.cpp \
		qrc_main.cpp
OBJECTS       = main.o \
		mainwindow.o \
		configurator.o \
		helpabout.o \
		operationguide.o \
		redcellantigens.o \
		moc_mainwindow.o \
		moc_configurator.o \
		moc_helpabout.o \
		moc_operationguide.o \
		moc_redcellantigens.o \
		qrc_main.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		RCcompat3.pro
QMAKE_TARGET  = RCcompat3
DESTDIR       = 
TARGET        = RCcompat3

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_configurator.h ui_helpabout.h ui_operationguide.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: RCcompat3.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile RCcompat3.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile RCcompat3.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/RCcompat31.0.0 || $(MKDIR) .tmp/RCcompat31.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/RCcompat31.0.0/ && $(COPY_FILE) --parents mainwindow.h configurator.h helpabout.h operationguide.h redcellantigens.h .tmp/RCcompat31.0.0/ && $(COPY_FILE) --parents main.qrc .tmp/RCcompat31.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp configurator.cpp helpabout.cpp operationguide.cpp redcellantigens.cpp .tmp/RCcompat31.0.0/ && $(COPY_FILE) --parents mainwindow.ui configurator.ui helpabout.ui operationguide.ui .tmp/RCcompat31.0.0/ && (cd `dirname .tmp/RCcompat31.0.0` && $(TAR) RCcompat31.0.0.tar RCcompat31.0.0 && $(COMPRESS) RCcompat31.0.0.tar) && $(MOVE) `dirname .tmp/RCcompat31.0.0`/RCcompat31.0.0.tar.gz . && $(DEL_FILE) -r .tmp/RCcompat31.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_configurator.cpp moc_helpabout.cpp moc_operationguide.cpp moc_redcellantigens.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_configurator.cpp moc_helpabout.cpp moc_operationguide.cpp moc_redcellantigens.cpp
moc_mainwindow.cpp: redcellantigens.h \
		helpabout.h \
		operationguide.h \
		configurator.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_configurator.cpp: configurator.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) configurator.h -o moc_configurator.cpp

moc_helpabout.cpp: helpabout.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) helpabout.h -o moc_helpabout.cpp

moc_operationguide.cpp: operationguide.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) operationguide.h -o moc_operationguide.cpp

moc_redcellantigens.cpp: redcellantigens.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) redcellantigens.h -o moc_redcellantigens.cpp

compiler_rcc_make_all: qrc_main.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_main.cpp
qrc_main.cpp: main.qrc \
		exit.png \
		config.png \
		qt.png \
		reset.png \
		rccompat3.png \
		help.png
	/usr/bin/rcc -name main main.qrc -o qrc_main.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_configurator.h ui_helpabout.h ui_operationguide.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_configurator.h ui_helpabout.h ui_operationguide.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_configurator.h: configurator.ui
	/usr/bin/uic-qt4 configurator.ui -o ui_configurator.h

ui_helpabout.h: helpabout.ui
	/usr/bin/uic-qt4 helpabout.ui -o ui_helpabout.h

ui_operationguide.h: operationguide.ui
	/usr/bin/uic-qt4 operationguide.ui -o ui_operationguide.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		redcellantigens.h \
		helpabout.h \
		operationguide.h \
		configurator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		redcellantigens.h \
		helpabout.h \
		operationguide.h \
		configurator.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

configurator.o: configurator.cpp configurator.h \
		ui_configurator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configurator.o configurator.cpp

helpabout.o: helpabout.cpp helpabout.h \
		ui_helpabout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helpabout.o helpabout.cpp

operationguide.o: operationguide.cpp operationguide.h \
		ui_operationguide.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o operationguide.o operationguide.cpp

redcellantigens.o: redcellantigens.cpp redcellantigens.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o redcellantigens.o redcellantigens.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_configurator.o: moc_configurator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configurator.o moc_configurator.cpp

moc_helpabout.o: moc_helpabout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_helpabout.o moc_helpabout.cpp

moc_operationguide.o: moc_operationguide.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_operationguide.o moc_operationguide.cpp

moc_redcellantigens.o: moc_redcellantigens.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_redcellantigens.o moc_redcellantigens.cpp

qrc_main.o: qrc_main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_main.o qrc_main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

